#!/usr/bin/env python3
"""Generate docs/SCRIPT_INDEX.md from workflow registries.

Run from the repository root:

    python3 scripts/generate_script_index.py

The index is generated only from machine-readable workflow files. It does not
scan scripts/, reference_configs/, resources/, or generated outputs.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "SCRIPT_INDEX.md"
SCRIPT_REGISTRY = ROOT / "workflow" / "script_registry.json"
EXECUTION_REGISTRY = ROOT / "workflow" / "execution_registry.json"
VALIDATION_POLICY = ROOT / "workflow" / "validation_policy.json"


def load_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as f:
        data = json.load(f)
    return data if isinstance(data, dict) else {}


def stringify(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, list):
        return " ".join(str(item) for item in value)
    if isinstance(value, dict):
        return ", ".join(f"{key}={stringify(item)}" for key, item in value.items())
    return str(value)


def cell(value: Any) -> str:
    text = stringify(value).strip() or "unknown"
    return text.replace("|", "\\|").replace("\n", "<br>")


def table(headers: list[str], rows: list[list[Any]]) -> list[str]:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    if rows:
        lines.extend("| " + " | ".join(cell(item) for item in row) + " |" for row in rows)
    else:
        lines.append("| " + " | ".join("unknown" for _ in headers) + " |")
    return lines


def common_script_rows(script_registry: dict[str, Any]) -> list[list[str]]:
    rows: list[list[str]] = []
    scripts = script_registry.get("scripts", {})
    if isinstance(scripts, dict):
        rows.extend([name, path] for name, path in sorted(scripts.items()))
    monitors = script_registry.get("monitors", {})
    if isinstance(monitors, dict):
        rows.extend([f"monitor:{name}", path] for name, path in sorted(monitors.items()))
    return rows


def adapter_rows(execution_registry: dict[str, Any]) -> list[list[Any]]:
    rows: list[list[Any]] = []
    adapters = execution_registry.get("generation_adapters", {})
    if not isinstance(adapters, dict):
        return rows
    for family, subtypes in sorted(adapters.items()):
        if not isinstance(subtypes, dict):
            rows.append([family, "unknown", "unknown", "", ""])
            continue
        for subtype, adapter in sorted(subtypes.items()):
            adapter = adapter if isinstance(adapter, dict) else {}
            rows.append(
                [
                    family,
                    subtype,
                    adapter.get("input_format", "unknown"),
                    adapter.get("command", []),
                    adapter.get("validator", []),
                ]
            )
    return rows


def validation_rows(validation_policy: dict[str, Any]) -> list[list[Any]]:
    rows: list[list[Any]] = []
    policies = validation_policy.get("policies", {})
    if not isinstance(policies, dict):
        return rows
    for family, policy in sorted(policies.items()):
        policy = policy if isinstance(policy, dict) else {}
        rows.append(
            [
                family,
                "family",
                policy.get("required_shape", ""),
                policy.get("main_workflow_layers", []),
                policy.get("rules_validator", policy.get("validators", [])),
                policy.get("reference_invariants", []),
            ]
        )
        subtype_validators = policy.get("subtype_validators", {})
        if isinstance(subtype_validators, dict):
            for subtype, subtype_policy in sorted(subtype_validators.items()):
                subtype_policy = subtype_policy if isinstance(subtype_policy, dict) else {}
                rows.append(
                    [
                        family,
                        subtype,
                        policy.get("required_shape", ""),
                        policy.get("main_workflow_layers", []),
                        subtype_policy.get("rules_validator", []),
                        subtype_policy.get("reference_invariants", []),
                    ]
                )
    return rows


def build_markdown(
    script_registry: dict[str, Any],
    execution_registry: dict[str, Any],
    validation_policy: dict[str, Any],
) -> str:
    lines: list[str] = [
        "# Script Index",
        "",
        "> Generated by `scripts/generate_script_index.py`. Do not edit this file by hand.",
        "",
        "Use this index to locate scripts before opening target files. Do not scan the whole `scripts/` directory by default.",
        "",
        "## Sources",
        "",
        "- `workflow/script_registry.json`",
        "- `workflow/execution_registry.json`",
        "- `workflow/validation_policy.json`",
        "",
        "## Common Workflow Scripts",
        "",
    ]
    lines.extend(table(["Name", "Path"], common_script_rows(script_registry)))
    lines.extend(
        [
            "",
            "## Generation Adapters",
            "",
        ]
    )
    lines.extend(
        table(
            ["Game Family", "Game Subtype", "Input Format", "Generator Command", "Validator"],
            adapter_rows(execution_registry),
        )
    )
    lines.extend(
        [
            "",
            "## Validation Policies",
            "",
        ]
    )
    lines.extend(
        table(
            ["Game Family", "Scope", "Required Shape", "Workflow Layers", "Rules Validator", "Reference Invariants"],
            validation_rows(validation_policy),
        )
    )
    lines.extend(
        [
            "",
            "## Script Location Principle",
            "",
            "1. Check this index first.",
            "2. Open only the target script or registry row needed for the current task.",
            "3. Do not scan the whole `scripts/` directory unless a registry entry is missing and the user asks you to investigate.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    markdown = build_markdown(
        load_json(SCRIPT_REGISTRY),
        load_json(EXECUTION_REGISTRY),
        load_json(VALIDATION_POLICY),
    )
    OUTPUT.write_text(markdown, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
